<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\MediaBundle\Entity;

use Sonata\MediaBundle\Entity\BaseGalleryHasMedia as BaseGalleryHasMedia;
use Doctrine\ORM\Mapping as ORM;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class GalleryHasMedia extends BaseGalleryHasMedia
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * @var bool Является ли картинка основной в галерее. Используется для превью галереи или сущности.
     */
    protected $main;
    
    /*
     * Constructor
     */
    public function __construct()
    {
        $this->main = false;
        parent::__construct();
        $this->enabled = true;
    }

    /**
     * Get id
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return bool
     */
    public function isMain(): bool
    {
        return $this->main;
    }
    
    /**
     * @return bool
     */
    public function getMain(): bool
    {
        return $this->main;
    }

    /**
     * @param bool $main
     *
     * @return GalleryHasMedia
     */
    public function setMain(bool $main): GalleryHasMedia
    {
        $this->main = $main;

        return $this;
    }
}
