<?php

namespace AppBundle\Entity\Repository;

/**
 * CmfScriptSelectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmfScriptSelectionRepository extends \Doctrine\ORM\EntityRepository
{
}
