<?php

namespace AppBundle\Entity\Repository;

/**
 * ItemSelectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemSelectionRepository extends \Doctrine\ORM\EntityRepository
{
}
