<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\Review;
/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends \Doctrine\ORM\EntityRepository
{

    /**
    * Получить список 
     *
     * @param array $options список 
     *
     * @return QueryBuilder
     */
    public function getItems($options = ['status' => 1])
    {
        $em = $this->getEntityManager();
        $select = $em->createQueryBuilder()
            ->select('c')
            ->from(Review::class, 'c')
            ->join('c.order', 'o')
            ->orderBy('c.createdAt', 'DESC');

        if (isset($options['status'])) {
            $select =$select
                ->andWhere('c.status = :status')
                ->setParameter('status', $options['status']);
        }

        if (isset($options['designer']) && $options['designer']) {
            $select->andWhere('o.executor = :designer')
                ->setParameter('designer', $options['designer']);
        }

        if (isset($options['item']) && $options['item']) {
            $select->andWhere('o.item = :item')
                ->setParameter('item', $options['item']);
        }

        return $select;
    }

}
