<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\Selection;

/**
 * SelectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SelectionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
    * Получить список выборок/коллекций
     *
     * @param array $options список фильтрации
     *
     * @return array
     */
    public function getItems($options)
    {
        $em = $this->getEntityManager();
        $select = $em->createQueryBuilder()
            ->select('c')
            ->from(Selection::class, 'c')
            ->where('c.status=1');

        if (isset($options['user']) && $options['user']) {
            $select =$select
                ->andWhere('c.user IN (:userIds)')
                ->setParameter('userIds', $options['user']);
        }

        if (isset($options['item']) && $options['item']) {
            $select =$select
                ->join('c.itemSelections', 'is')
                ->andWhere('is.item IN (:itemIds)')
                ->setParameter('userIds', $options['item']);
        }

        return $select;
    }

}
